name: Deploy Feedback Platform to Azure

on:
  push:
    branches:
      - master

jobs:
  infra-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Infrastructure (IaC)
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: cloud-shell-storage-eastus
          template: ./main.bicep
          region: eastus
          parameters: >
            smtpHost=${{ secrets.SMTP_HOST }}
            smtpPort=${{ secrets.SMTP_PORT }}
            smtpUser=${{ secrets.SMTP_USER }}
            smtpPassword=${{ secrets.SMTP_PASSWORD }}
            mailTo=${{ secrets.MAIL_TO }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Project with Maven
        run: mvn clean package

      - name: Deploy Java Function to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: 'fnapp-feedback-platform'
          package: './target/azure-functions/fnapp-feedback-platform'